package gocrud

import (
	"errors"
	"net/http"
	"os"
	"path"

	"github.com/gin-gonic/gin"
)

const (
	XFileDigest = "X-File-Digest"
)

var (
	ErrorIncompleteWrite            = errors.New("incomplete write")
	ErrorFileIsDir                  = errors.New("file is a directory")
	ErrorUploadNotAllowed           = errors.New("upload not allowed")
	ErrorFileDigestMismatch         = errors.New("digest mismatch")
	ErrorFileMasterKeyMustBe32Bytes = errors.New("master key must be 32 bytes")
	ErrorFileKeyProviderIsNil       = errors.New("file key provider is nil")
)

type (
	Filename   string
	FileSize   int64
	FileDigest string

	// FileNoncedDigest
	// This is generated by FileDigest and FileNonce
	FileNoncedDigest string

	// FileNonce
	// Use this to generate FileKey From FileMasterKey,
	// this also involves the generation of FileDigest
	FileNonce []byte
	// FileMasterKey
	// This should be saved securely, all FileKey-s are derived from this
	FileMasterKey []byte
	FileKey       []byte
)

type HttpFile struct {
	Filename     Filename
	Length       FileSize
	Digest       FileDigest
	Nonce        FileNonce
	NoncedDigest FileNoncedDigest
	FileKey      FileKey
}

type HttpFileSystemConfig struct {
	AllowUpload bool

	// EnableDigest
	// if true, will save file with its digest, and discard client defined filename
	//
	// DEPRECATED: forced be digested now
	//EnableDigest bool

	FileMasterKey  FileMasterKey
	OnFileReview   func(filename Filename) (*HttpFile, error)
	OnFileDigested func(digest FileDigest, noncedDigest FileNoncedDigest) (*HttpFile, error)
	OnFileSaved    func(file *HttpFile) error

	Coder Coder
}

func NewHttpFileSystemController(group *gin.RouterGroup, folder string, config *HttpFileSystemConfig) error {
	if config == nil {
		config = &HttpFileSystemConfig{Coder: RestCoder}
	}

	if config.Coder == nil {
		config.Coder = RestCoder
	}

	if config.FileMasterKey == nil {
		group.Static("", folder)
	} else {
		if config.OnFileReview == nil {
			return ErrorFileKeyProviderIsNil
		}

		group.GET("/*filepath", func(context *gin.Context) {
			httpFile, err := config.OnFileReview(Filename(context.Param("filepath")))
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
			if httpFile == nil {
				MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
				return
			}

			filePath := path.Join(folder, string(httpFile.Filename))
			file, err := os.Open(filePath)
			if err != nil {
				if os.IsNotExist(err) {
					MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
					return
				}
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
			defer func() {
				_ = file.Close()
			}()

			serveFunc, err := NewDareHttpServeFunc(file, httpFile)
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}

			serveFunc(context.Writer, context.Request)
		})
	}

	uploadHandler := func(context *gin.Context) {
		if !config.AllowUpload {
			MakeErrorResponse(context, config.Coder.MethodNotAllowed(), ErrorUploadNotAllowed)
			return
		}

		file, err := SaveDareFile(
			context.Request.Body,
			&SaveDareFileConfig{
				BaseFolder:     folder,
				Ext:            path.Ext(path.Base(context.Param("filepath"))),
				Length:         FileSize(context.Request.ContentLength),
				Validigest:     FileDigest(context.GetHeader(XFileDigest)),
				MasterKey:      config.FileMasterKey,
				OnFileDigested: config.OnFileDigested,
			},
		)
		if err != nil {
			MakeErrorResponse(context, config.Coder.InternalServerError(), err)
			return
		}

		if config.OnFileSaved != nil {
			err := config.OnFileSaved(file)
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
		}

		context.JSON(http.StatusOK, R[string]{
			Code: config.Coder.OK(),
			Data: string(file.Filename),
		})
	}

	group.POST("/*filepath", uploadHandler)
	group.PUT("/*filepath", uploadHandler)

	return nil
}
