package gocrud

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"path"
	"reflect"
	"strings"
	"time"

	"github.com/allape/gogger"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

const (
	XFileDigest = "X-File-Digest"
)

var (
	ErrorIncompleteWrite            = errors.New("incomplete write")
	ErrorFileIsDir                  = errors.New("file is a directory")
	ErrorUploadNotAllowed           = errors.New("upload not allowed")
	ErrorFileDigestMismatch         = errors.New("digest mismatch")
	ErrorFileMasterKeyMustBe32Bytes = errors.New("master key must be 32 bytes")
	ErrorFileKeyProviderIsNil       = errors.New("file key provider is nil")
)

type (
	Filename   string
	FileSize   int64
	FileDigest string

	// FileNoncedDigest
	// This is generated by FileDigest and FileNonce
	FileNoncedDigest string

	// FileNonce
	// Use this to generate FileKey From FileMasterKey,
	// this also involves the generation of FileDigest
	FileNonce []byte
	// FileMasterKey
	// This should be saved securely, all FileKey-s are derived from this
	FileMasterKey []byte
	FileKey       []byte
)

type HttpFile struct {
	Filename     Filename
	Length       FileSize
	Digest       FileDigest
	Nonce        FileNonce
	NoncedDigest FileNoncedDigest
	FileKey      FileKey
}

type HttpFileSystemConfig struct {
	AllowUpload bool

	// EnableDigest
	// if true, will save file with its digest, and discard client defined filename
	//
	// DEPRECATED: forced be digested now
	//EnableDigest bool

	FileMasterKey  FileMasterKey
	OnFileReview   func(filename Filename) (*HttpFile, error)
	OnFileDigested func(digest FileDigest) (*HttpFile, error)
	OnFileSaved    func(file *HttpFile) error

	Coder Coder
}

func NewHttpFileSystemController(group *gin.RouterGroup, folder string, config *HttpFileSystemConfig) error {
	if config == nil {
		config = &HttpFileSystemConfig{Coder: RestCoder}
	}

	if config.Coder == nil {
		config.Coder = RestCoder
	}

	if config.FileMasterKey == nil {
		group.Static("", folder)
	} else {
		if config.OnFileReview == nil {
			return ErrorFileKeyProviderIsNil
		}

		group.GET("/*filepath", func(context *gin.Context) {
			httpFile, err := config.OnFileReview(Filename(context.Param("filepath")))
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
			if httpFile == nil {
				MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
				return
			}

			filePath := path.Join(folder, string(httpFile.Filename))
			file, err := os.Open(filePath)
			if err != nil {
				if os.IsNotExist(err) {
					MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
					return
				}
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
			defer func() {
				_ = file.Close()
			}()

			serveFunc, err := ServeDareContentHandler(file, httpFile)
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}

			serveFunc(context.Writer, context.Request)
		})
	}

	uploadHandler := func(context *gin.Context) {
		if !config.AllowUpload {
			MakeErrorResponse(context, config.Coder.MethodNotAllowed(), ErrorUploadNotAllowed)
			return
		}

		file, err := SaveFileDarelly(
			context.Request.Body,
			&SaveFileDarellyConfig{
				BaseFolder:     folder,
				Ext:            path.Ext(path.Base(context.Param("filepath"))),
				Length:         FileSize(context.Request.ContentLength),
				Validigest:     FileDigest(context.GetHeader(XFileDigest)),
				MasterKey:      config.FileMasterKey,
				OnFileDigested: config.OnFileDigested,
			},
		)
		if err != nil {
			MakeErrorResponse(context, config.Coder.InternalServerError(), err)
			return
		}

		if config.OnFileSaved != nil {
			err := config.OnFileSaved(file)
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}
		}

		context.JSON(http.StatusOK, R[string]{
			Code: config.Coder.OK(),
			Data: string(file.Filename),
		})
	}

	group.POST("/*filepath", uploadHandler)
	group.PUT("/*filepath", uploadHandler)

	return nil
}

type HttpFileSystemObjectBase struct {
	HttpFile

	Filename     Filename         `json:"filename"`
	Length       FileSize         `json:"length"`
	Digest       FileDigest       `json:"digest" gorm:"index"`
	Nonce        FileNonce        `json:"nonce"`
	NoncedDigest FileNoncedDigest `json:"noncedDigest" gorm:"primaryKey"`
	FileKey      FileKey          `json:"fileKey"`
	CreatedAt    time.Time        `json:"createdAt" gorm:"autoCreateTime;<-:create"`
}

func (obj *HttpFileSystemObjectBase) ToHttpFile() *HttpFile {
	return &HttpFile{
		Filename:     obj.Filename,
		Length:       obj.Length,
		Digest:       obj.Digest,
		Nonce:        obj.Nonce,
		NoncedDigest: obj.NoncedDigest,
		FileKey:      obj.FileKey,
	}
}

func (obj *HttpFileSystemObjectBase) FromHttpFile(file *HttpFile) {
	obj.Filename = file.Filename
	obj.Length = file.Length
	obj.Digest = file.Digest
	obj.Nonce = file.Nonce
	obj.NoncedDigest = file.NoncedDigest
	obj.FileKey = file.FileKey
}

// NewHttpFileSystemObjectController
// T must be extended from HttpFileSystemObjectBase
// baseStructFieldName will be HttpFileSystemObjectBase if empty
func NewHttpFileSystemObjectController[T any](
	group *gin.RouterGroup, db *gorm.DB, logger *gogger.Logger,
	folder string, config *HttpFileSystemConfig,
	baseStructFieldName string,
) error {
	if baseStructFieldName == "" {
		reflected := reflect.TypeFor[HttpFileSystemObjectBase]()
		baseStructFieldName = reflected.Name()
	}

	// precheck
	{
		reflected := reflect.TypeFor[T]()

		baseStructField, ok := reflected.FieldByName(baseStructFieldName)
		if !ok {
			return fmt.Errorf("baseStructField %s not found", baseStructFieldName)
		}

		baseStructFieldType := baseStructField.Type

		if baseStructFieldType.Kind() == reflect.Pointer {
			baseStructFieldType = baseStructFieldType.Elem()
		}

		if baseStructFieldType.Kind() != reflect.Struct {
			return fmt.Errorf("baseStructFieldType %s is not a struct", baseStructFieldType)
		}

		fileSystemObjectBaseType := reflect.TypeFor[HttpFileSystemObjectBase]()

		if !baseStructFieldType.ConvertibleTo(fileSystemObjectBaseType) {
			return fmt.Errorf(
				"baseStructField %s should be a type of %s, but got %s",
				baseStructFieldName,
				fileSystemObjectBaseType.Name(),
				baseStructFieldType.Name(),
			)
		}
	}

	err := db.AutoMigrate(new(T))
	if err != nil {
		return err
	}

	getObjectBase := func(record *T) (*HttpFileSystemObjectBase, error) {
		value := reflect.ValueOf(record).Elem().FieldByName(baseStructFieldName)

		if value.Kind() == reflect.Pointer {
			value = value.Elem()
		}

		obj, ok := value.Interface().(HttpFileSystemObjectBase)
		if !ok {
			return nil, fmt.Errorf("unexpected type %T", record)
		}

		return &obj, nil
	}

	setObjectBase := func(record *T, obj *HttpFileSystemObjectBase) error {
		value := reflect.ValueOf(record).Elem().FieldByName(baseStructFieldName)
		if value.Kind() == reflect.Pointer {
			value = value.Elem()
		}
		value.Set(reflect.ValueOf(obj).Elem())
		return nil
	}

	config.OnFileReview = func(filename Filename) (*HttpFile, error) {
		noncedDigest := path.Base(string(filename))
		dotIndex := strings.Index(noncedDigest, ".")
		if dotIndex >= 0 {
			noncedDigest = noncedDigest[:dotIndex]
		}

		if noncedDigest == "" {
			return nil, nil
		}

		var records []T
		if err = db.Model(new(T)).Where("`nonced_digest` = ?", noncedDigest).Find(&records).Error; err != nil {
			logger.Error().Printf("OnFileReview: failed to find file object %s:%s:%s, err: %s", folder, filename, noncedDigest, err)
			return nil, err
		}

		if len(records) == 0 {
			return nil, nil
		}

		obj, err := getObjectBase(&records[0])
		if err != nil {
			return nil, err
		}

		return obj.ToHttpFile(), nil
	}

	config.OnFileDigested = func(digest FileDigest) (*HttpFile, error) {
		var records []T
		if err = db.Model(new(T)).Where("`digest` = ?", digest).Find(&records).Error; err != nil {
			logger.Error().Printf("OnFileDigested: failed to find file object %s:%s, err: %s", folder, digest, err)
			return nil, err
		}

		if len(records) == 0 {
			return nil, nil
		}

		obj, err := getObjectBase(&records[0])
		if err != nil {
			return nil, err
		}

		return obj.ToHttpFile(), nil
	}

	config.OnFileSaved = func(file *HttpFile) error {
		var record T
		obj, err := getObjectBase(&record)
		if err != nil {
			return err
		}

		obj.FromHttpFile(file)
		err = setObjectBase(&record, obj)
		if err != nil {
			return err
		}

		if err := db.Model(&record).Save(&record).Error; err != nil {
			return err
		}

		return nil
	}

	return NewHttpFileSystemController(group, folder, config)
}
