package gocrud

import (
	"errors"
	"net/http"
	"os"
	"path"
	"time"

	"github.com/gin-gonic/gin"
)

const (
	XFileDigest = "X-File-Digest"
)

var (
	ErrorIncompleteWrite            = errors.New("incomplete write")
	ErrorFileIsDir                  = errors.New("file is a directory")
	ErrorUploadNotAllowed           = errors.New("upload not allowed")
	ErrorFileDigestMismatch         = errors.New("digest mismatch")
	ErrorFileMasterKeyMustBe32Bytes = errors.New("master key must be 32 bytes")
	ErrorFileNonceMustBe32Bytes     = errors.New("file nonce must be 32 bytes")
	ErrorFileKeyProviderIsNil       = errors.New("file key provider is nil")
)

type (
	Filename   string
	FileSize   int64
	FileDigest string

	// FileNoncedDigest
	// This is generated by FileDigest and FileNonce
	FileNoncedDigest string

	// FileNonce
	// Use this to generate FileKey From FileMasterKey,
	// this also involves the generation of FileDigest
	FileNonce []byte
	// FileMasterKey
	// This should be saved securely, all FileKey-s are derived from this
	FileMasterKey []byte
	FileKey       []byte
)

type HttpFile struct {
	Filename     Filename
	Length       FileSize
	Digest       FileDigest
	Nonce        FileNonce
	NoncedDigest FileNoncedDigest
	FileKey      FileKey
}

type HttpFileSystemConfig struct {
	AllowUpload bool

	// EnableDigest
	// if true, will save file with its digest, and discard client defined filename
	//
	// DEPRECATED: forced be digested now
	//EnableDigest bool

	FileMasterKey FileMasterKey

	FileKeyProvider func(filename string) (Filename, FileSize, FileKey)
	OnFileSaved     func(file *HttpFile)

	Coder Coder
}

func NewHttpFileSystem(group *gin.RouterGroup, folder string, config *HttpFileSystemConfig) error {
	if config == nil {
		config = &HttpFileSystemConfig{Coder: RestCoder}
	}

	if config.Coder == nil {
		config.Coder = RestCoder
	}

	if config.FileMasterKey == nil {
		group.Static("", folder)
	} else {
		if config.FileKeyProvider == nil {
			return ErrorFileKeyProviderIsNil
		}

		group.GET("/*filepath", func(context *gin.Context) {
			filename, fileSize, fileKey := config.FileKeyProvider(context.Param("filepath"))
			if filename == "" || fileSize == 0 || fileKey == nil {
				MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
				return
			}

			filePath := path.Join(folder, string(filename))
			file, err := os.Open(filePath)
			if err != nil {
				if os.IsNotExist(err) {
					MakeErrorResponse(context, config.Coder.NotFound(), http.StatusText(http.StatusNotFound))
					return
				}
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
			}

			reader, err := NewDareReader(file, fileSize, fileKey)
			if err != nil {
				MakeErrorResponse(context, config.Coder.InternalServerError(), err)
				return
			}

			//mimeType := mime.TypeByExtension(filepath.Ext(string(filename)))
			//if mimeType == "" {
			//	mimeType = "application/octet-stream"
			//}
			//context.Header("Content-Type", mimeType)

			http.ServeContent(context.Writer, context.Request, path.Base(string(filename)), time.UnixMilli(0), reader)
		})
	}

	uploadHandler := func(context *gin.Context) {
		if !config.AllowUpload {
			MakeErrorResponse(context, config.Coder.MethodNotAllowed(), ErrorUploadNotAllowed)
			return
		}

		file, err := SaveFileDarelly(
			context.Request.Body,
			&SaveFileDarellyConfig{
				BaseFolder: folder,
				Ext:        path.Ext(path.Base(context.Param("filepath"))),
				Length:     FileSize(context.Request.ContentLength),
				Validigest: FileDigest(context.GetHeader(XFileDigest)),
				MasterKey:  config.FileMasterKey,
			},
		)
		if err != nil {
			MakeErrorResponse(context, config.Coder.InternalServerError(), err)
			return
		}

		if config.OnFileSaved != nil {
			config.OnFileSaved(file)
		}

		context.JSON(http.StatusOK, R[string]{
			Code: config.Coder.OK(),
			Data: string(file.Filename),
		})
	}

	group.POST("/*filepath", uploadHandler)
	group.PUT("/*filepath", uploadHandler)

	return nil
}
